name: Newman API Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g newman newman-reporter-htmlextra json-server

      - name: Run API Tests
        run: |
          # Spust mock server na pozadi
          json-server --watch db.json --routes routes.json --port 3000 > server.log 2>&1 &
          
          # Cekani na server
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then break; fi
            sleep 2
          done
          
          # Zamena URL v kolekci
          sed -i 's|https://fakestoreapi.com|http://localhost:3000|g' ecommerce-api-collection.postman_collection.json
          
          # Spusteni testu
          newman run ecommerce-api-collection.postman_collection.json \
          -e ecommerce-environment.postman_environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export report.html

      - name: Archive HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: report.html