name: Newman API Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Klonovani repozitare
      - uses: actions/checkout@v3

      # 2. Instalace Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalace Newmana a HTML reporteru
      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      # 4. Spusteni testu a generovani reportu
      - name: Run API Tests
        run: |
          newman run ecommerce-api-collection.postman_collection.json \
          -e ecommerce-environment.postman_environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export report.html
      # 5. Archivace HTML reportu jako artefaktu (opravena verze na v4)
      - name: Archive HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: report.html